### ISSUE TITLE
Flutter unity widget - Unity Sentry SDK

### ISSUE THREAD

**Issue by Eunyoung-jeong** [getsentry/sentry-unity#1546]
Hello. I am currently implementing an app using Flutter's Unity widget. I have applied the Sentry Unity SDK for Unity bug reporting, and when I build the app and finally run it on Flutter for Android, a crash occurs.

E  FATAL EXCEPTION: main
                                                                                                    Process: com.lguplus.pickids, PID: 19054
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/SentryDateProvider;
                                                                                                        at io.sentry.android.core.AndroidDateUtils.getCurrentSentryDateTime(AndroidDateUtils.java:22)
                                                                                                        at io.sentry.android.core.SentryPerformanceProvider.<clinit>(SentryPerformanceProvider.java:27)
                                                                                                        at java.lang.Class.newInstance(Native Method)
                                                                                                        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
                                                                                                        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:66)
                                                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:8309)
                                                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7822)
                                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7576)
                                                                                                        at android.app.ActivityThread.access$1800(ActivityThread.java:319)
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2326)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                        at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                        at android.os.Looper.loop(Looper.java:313)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.sentry.SentryDateProvider" on path: DexPathList[[zip file "/data/app/~~uWCWhbTFUrSqPG2lfgltqA==/com.lguplus.pickids-hYL_uCwgY0gMF6Va_Zr3gw==/base.apk"],nativeLibraryDirectories=[/data/app/~~uWCWhbTFUrSqPG2lfgltqA==/com.lguplus.pickids-hYL_uCwgY0gMF6Va_Zr3gw==/lib/arm64, /data/app/~~uWCWhbTFUrSqPG2lfgltqA==/com.lguplus.pickids-hYL_uCwgY0gMF6Va_Zr3gw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                        at io.sentry.android.core.AndroidDateUtils.getCurrentSentryDateTime(AndroidDateUtils.java:22) 
                                                                                                        at io.sentry.android.core.SentryPerformanceProvider.<clinit>(SentryPerformanceProvider.java:27) 
                                                                                                        at java.lang.Class.newInstance(Native Method) 
                                                                                                        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147) 
                                                                                                        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:66) 
                                                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:8309) 
                                                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7822) 
                                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7576) 
                                                                                                        at android.app.ActivityThread.access$1800(ActivityThread.java:319) 
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2326) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                        at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                        at android.os.Looper.loop(Looper.java:313) 
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by bitsandfoxes** [comment]
Hey there! Sorry to see you run into issues.
To unblock you, could you try disabling `Android Native Support` in the Unity project?

**Comment by Eunyoung-jeong** [comment]
@bitsandfoxes I want to build AOS, iOS application, using flutter - Unity Widget (with Sentry Unity SDK).....

**Comment by bitsandfoxes** [comment]
Could you try exporting your game with native support disabled?
![image](https://github.com/getsentry/sentry-unity/assets/25725783/a7b29e72-fba4-4934-af20-fa6beb1e59e4)
